# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
