# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170326_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='games/'),
        ),
    ]
