# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.FileField(blank=True, upload_to='files/games/'),
        ),
    ]
